# Generated by Django 5.0.2 on 2024-02-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentManagement', '0002_student_date_joined_student_is_registered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
