# Generated by Django 5.0.2 on 2024-02-24 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentManagement', '0003_alter_student_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mentor_number', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='mentor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='studentManagement.mentor'),
            preserve_default=False,
        ),
    ]
