# Generated by Django 5.0.2 on 2024-02-24 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentManagement', '0004_mentor_student_mentor'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField()),
                ('account_name', models.CharField(max_length=250)),
                ('bank_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='mentor',
            name='bank_details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='studentManagement.bankdetails'),
        ),
    ]
