# Generated by Django 5.0.2 on 2024-02-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentManagement', '0005_bankdetails_mentor_bank_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='bankdetails',
            options={'verbose_name_plural': 'Bank Details'},
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(to='studentManagement.course'),
        ),
    ]
