# Generated by Django 5.0.2 on 2024-03-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='screenshot',
            field=models.FileField(blank=True, upload_to='screenshots/'),
        ),
    ]
