# Generated by Django 5.0.2 on 2024-03-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_contactus_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='screenshot',
            field=models.ImageField(blank=True, upload_to='screenshots/'),
        ),
    ]
